<Project>
  <Target Name="_NodeBuildBun"
          AfterTargets="NodeBuild"
          Condition="'@(NodeSelectedPackageManager)' == 'bun' and '@(NodeSelectedPackageManager->'%(OwnsBuild)')' == 'true'">
    <Exec WorkingDirectory="$(NodeRootFullPath)"
          Command="bun run build @(NodeBuildArgument->'%(Identity) %(Value)', ' ')"
          EnvironmentVariables="NODE_ENV=$(NodeBuildConfiguration)" />
  </Target>
</Project>
