<Project>
  <PropertyGroup>
    <NodePackageManagerDetectDependsOn>$(NodePackageManagerDetectDependsOn);_NodeToolchainYarnDetect</NodePackageManagerDetectDependsOn>
  </PropertyGroup>

  <Target Name="_NodeToolchainYarnDetect">
    <PropertyGroup>
      <_NodeToolchainYarnRootPath>$([MSBuild]::GetDirectoryNameOfFileAbove('$(NodeRootFullPath)', 'yarn.lock'))</_NodeToolchainYarnRootPath>
    </PropertyGroup>
    <ItemGroup Condition="'$(_NodeToolchainYarnRootPath)' != '' or '$(NodePackageManager)' == 'yarn'">
      <_NodePackageManagerCandidate Include="yarn">
        <Priority>190</Priority>
        <RootPath Condition="'$(_NodeToolchainYarnRootPath)' != ''">$(_NodeToolchainYarnRootPath)</RootPath>
        <RootPath Condition="'$(_NodeToolchainYarnRootPath)' == ''">$(NodeRootFullPath)</RootPath>
        <Source>$(MSBuildThisFileFullPath)</Source>
      </_NodePackageManagerCandidate>
    </ItemGroup>
  </Target>
</Project>
